### ISSUE TITLE
Add comment to tag "alt" to improve accessibility

### ISSUE THREAD

**Issue by luisdasilvahenrique** [PriscilaZeferino/DesafioCodar_DevChallenge#1]
https://github.com/PriscilaZeferino/DesafioCodar_DevChallenge/blob/596e6bd0713bd2bef09a91ffee4a98d8f9c80abb/index.html#L25

**Comment by luisdasilvahenrique** [comment]
Só quero procurar ajudar, sou bem novo nisso ainda, e vi que está em uma constante evolução e sempre procuro me aperfeiçoar em projeto que encontro e achei super incrível o seu.

**Comment by PriscilaZeferino** [comment]
Ah, sim, farei isso. Obrigada!
